### ISSUE TITLE
ToggleOrmolu messages

### ISSUE THREAD

**Issue by jonathanlking** [sdiehl/vim-ormolu#1]
I believe the `"Ormolu formatting ..."` messages should be the other way around. 
Also should `DisableOrmolu` instead set `ormolu_disable = 1`?
 
https://github.com/sdiehl/vim-ormolu/blob/9517c118c2bf844dd07df1e6b711e1f661678871/ftplugin/haskell/ormolu-haskell.vim#L51-L63

Thanks for the plugin, it's greatly appreciated!

**Comment by sdiehl** [comment]
Thanks for noticing, I pushed the fix.
