### ISSUE TITLE
Possibility to format visual selection

### ISSUE THREAD

**Issue by denibertovic** [sdiehl/vim-ormolu#3]
Hey, thanks for this plugin! :cake: 

I've just recently switched to ormolu from hindent and was wondering if it's possible to format just a part of the code (visual selection) like it was possible with alx741/vim-hindent? From what I can tell the plugin doesn't support this but I'm not sure if that's because ormolu only works with files or if it's just something that didn't get implemented when writing the plugin?

The rationale being that I don't want to format an entire file in an existing codebase but I might want to format new code that's being added.

**Comment by sdiehl** [comment]
Hmm, this is a good idea. I'll look into it. I think it should be possible.
