### ISSUE TITLE
ormolu_disable not working

### ISSUE THREAD

**Issue by denibertovic** [sdiehl/vim-ormolu#5]
I've added `let g:ormolu_disable=1` in my .vimrc but the entire file still gets formatted on each write.
I'm not sure if I'm doing something wrong, or if I'm misunderstanding what the above setting does or if this is in fact a bug.

**Comment by sdiehl** [comment]
Fixed in https://github.com/sdiehl/vim-ormolu/commit/15cd34b217154d3141495a288d9e692fd826c80d.

**Comment by denibertovic** [comment]
@sdiehl Thanks. I've verified that it works now. However, ToggleOrmolu seems to be broken now.
