### ISSUE TITLE
ToggleOrmolu appears to be broken

### ISSUE THREAD

**Issue by denibertovic** [sdiehl/vim-ormolu#6]
Hey @sdiehl I think this bug was introduced with https://github.com/sdiehl/vim-ormolu/commit/15cd34b217154d3141495a288d9e692fd826c80d

**Comment by sdiehl** [comment]
You have the global disable flag on and you want ToggleOrmolu to override the global setting?

**Comment by sdiehl** [comment]
PR #7 should fix your issue. Let me know if this works as you expect.

**Comment by denibertovic** [comment]
@sdiehl Yes this is the use-case. It seemed like a useful thing to be able to do especially for working on new modules in an existing code-base (ie. new modules can get autoformatted on save).  Let me try out the PR and I'll comment there.
