### ISSUE TITLE
Run ormolu over the (possibly unsaved) contents of the buffer

### ISSUE THREAD

**Issue by mitchellwrosen** [sdiehl/vim-ormolu#9]
Currently, `vim-ormolu` requires you to save a file before formatting it. Would it be possible to run `ormolu` over the contents of the buffer instead?

**Comment by sdiehl** [comment]
This was trivial to add. I patched it in beb1423. 

In your buffer run:

```vim
set filetype=haskell
```

Then you can invoke whatever commands you like `:call RunOrmolu()` or `:call OrmoluBlock()` on the contents of the unsaved buffer.

**Comment by mitchellwrosen** [comment]
Thanks!! :)
